// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqcbgwlsozejljvnrdpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxY2Jnd2xzb3plamxqdm5yZHB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTY5OTIsImV4cCI6MjA2NTQ3Mjk5Mn0.UEBI2yStqlUF-LKQWZigdREZZidIxwZuku800jt3cfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);